using System.Text.Json.Serialization;
using JMAP.Net.Capabilities.Core.Types;
using JSCalendar.Net;

namespace JMAP.Net.Capabilities.Calendars.Types;

/// <summary>
/// Represents a JMAP CalendarEvent - a JSCalendar Event with additional JMAP properties.
/// As per JMAP Calendars RFC, Section 5.
/// </summary>
public class CalendarEvent : Event
{
    /// <summary>
    /// The id of the CalendarEvent (JMAP-specific, not the JSCalendar uid).
    /// Immutable; server-set.
    /// </summary>
    [JsonPropertyName("id")]
    public JmapId? Id { get; init; }

    /// <summary>
    /// Only defined if the id is a synthetic id generated by the server for a specific
    /// instance of a recurring event. This gives the id of the "real" CalendarEvent.
    /// Immutable; server-set.
    /// </summary>
    [JsonPropertyName("baseEventId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JmapId? BaseEventId { get; init; }

    /// <summary>
    /// The set of Calendar ids this event belongs to.
    /// An event must belong to one or more Calendars at all times.
    /// </summary>
    [JsonPropertyName("calendarIds")]
    public Dictionary<JmapId, bool>? CalendarIds { get; init; }

    /// <summary>
    /// If true, this event is a draft. The server will not send scheduling messages.
    /// May only be set to true upon creation. Once false, cannot be changed back to true.
    /// Default: false.
    /// </summary>
    [JsonPropertyName("isDraft")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsDraft { get; init; } = false;

    /// <summary>
    /// Server-set. Is this the authoritative source for this event?
    /// True if the event's replyTo is null or the account will receive messages
    /// sent to at least one of the replyTo methods.
    /// </summary>
    [JsonPropertyName("isOrigin")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsOrigin { get; init; }

    /// <summary>
    /// For simple clients that don't implement time zone support.
    /// Calculated at fetch time by the server.
    /// Not included by default - must be requested explicitly.
    /// </summary>
    [JsonPropertyName("utcStart")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JmapUtcDate? UtcStart { get; init; }

    /// <summary>
    /// The end time in UTC, calculated from start/timeZone/duration.
    /// Not included by default - must be requested explicitly.
    /// </summary>
    [JsonPropertyName("utcEnd")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JmapUtcDate? UtcEnd { get; init; }

    /// <summary>
    /// If true, any user may add themselves to the event as a participant 
    /// with the "attendee" role. This property MUST NOT be altered in 
    /// recurrenceOverrides; it may only be set on the base object.
    /// Default: false
    /// As per RFC 8984, Section 5.1.1.
    /// </summary>
    [JsonPropertyName("mayInviteSelf")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool MayInviteSelf { get; init; }

    /// <summary>
    /// If true, any current participant with the "attendee" role may add 
    /// new participants with the "attendee" role to the event. 
    /// This property MUST NOT be altered in recurrenceOverrides; 
    /// it may only be set on the base object.
    /// Default: false
    /// As per RFC 8984, Section 5.1.2.
    /// </summary>
    [JsonPropertyName("mayInviteOthers")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool MayInviteOthers { get; init; }

    /// <summary>
    /// If true, only the owners of the event may see the full set of participants.
    /// Other sharees of the event may only see the owners and themselves.
    /// This property MUST NOT be altered in recurrenceOverrides; 
    /// it may only be set on the base object.
    /// Default: false
    /// As per RFC 8984, Section 5.1.3.
    /// </summary>
    [JsonPropertyName("hideAttendees")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool HideAttendees { get; init; }
}
