using JMAP.Net.Capabilities.Core.Methods;

namespace JMAP.Net.Capabilities.Calendars.Methods.CalendarEvent;

/// <summary>
/// Request for CalendarEvent/changes method.
/// As per JMAP Calendars RFC, Section 5.8.
/// </summary>
public class CalendarEventChangesRequest : ChangesRequest
{
    // Inherits all properties from ChangesRequest:
    // - AccountId
    // - SinceState
    // - MaxChanges (optional)
    
    // Note: Synthetic ids generated by expanding recurrences do NOT appear in changes responses.
    // Only the ids of events as actually stored on the server are returned.
}
